// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutFeaturesSplit
          tag="Sobre mí"
          title="Iván, tu aliado digital"
          description="Soy Iván, diseñador web especializado en crear páginas modernas, rápidas y optimizadas para empresas. Durante los últimos 3 años he ayudado a negocios de diversos sectores a mejorar su presencia online mediante soluciones enfocadas en resultados."
          items={[
            { icon: "Rocket", title: "Velocidad", description: "Páginas cargadas en milisegundos." },
            { icon: "Search", title: "SEO Optimizado", description: "Estructura preparada para Google." },
            { icon: "Smartphone", title: "Responsive", description: "Adaptación perfecta en cualquier dispositivo." },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/man-working-laptop-purple-neon-light_23-2152013711.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
