// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contacto" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactoSection(): React.JSX.Element {
  return (
    <div id="contacto" data-section="contacto">
        <SectionErrorBoundary name="contacto">
              <ContactCta
          tag="Contacto"
          text="¿Listo para llevar tu negocio al siguiente nivel digital?"
          primaryButton={{
            text: "Solicitar presupuesto",        href: "mailto:contacto@ivandisenoweb.com"}}
          secondaryButton={{
            text: "WhatsApp   6366453

",        href: ""}}
        />
        </SectionErrorBoundary>
      </div>
  );
}
