/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Button from "@/components/ui/Button";

const primaryButton = {
  text: "Solicitar presupuesto",
  href: "mailto:contacto@ivandisenoweb.com"
};
const secondaryButton = {
  text: "WhatsApp 636645341",
  href: "https://wa.me/636645341"
};

const ContactoInline = () => {
  return (
    <section aria-label="Contact section" className="py-20">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="fade">
          <div className="flex flex-col items-center gap-8 md:gap-10 py-20 px-8 rounded card">
            <div className="flex flex-col items-center gap-2">
              <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
                <p>{"Contacto"}</p>
              </div>

              <TextAnimation
                text={"¿Listo para llevar tu negocio al siguiente nivel digital?"}
                variant="fade"
                gradientText={true}
                tag="h2"
                className="md:max-w-8/10 text-5xl 2xl:text-6xl leading-[1.15] font-semibold text-center text-balance"
              />

              <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
                <Button text={primaryButton.text} href={primaryButton.href} variant="primary" />
                <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary" animationDelay={0.1} />
              </div>
              <p className="text-accent mt-4 text-sm md:text-base">
                ¿Prefieres hablar? Llámanos o escríbenos al <a href="https://wa.me/34636645341" className="text-foreground underline hover:no-underline transition-all">+34 636 645 341</a>
              </p>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ContactoSection() {
  return (
    <div data-webild-section="contacto" id="contacto">
      <ContactoInline />
    </div>
  );
}
