// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection): React.JSX.Element {
  return 
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSimple
          tag="Dudas comunes"
          title="Preguntas frecuentes"
          description="Información clave sobre mis servicios profesionales."
          items={[
            { question: "¿Cuánto tardas en hacer una web?", answer: "Normalmente entrego el proyecto en unas 24 horas dependiendo del tamaño y complejidad." },
            { question: "¿La web es responsive?", answer: "Sí, todas mis entregas están totalmente adaptadas a móviles, tablets y ordenadores." },
            { question: "¿Incluyes SEO?", answer: "Sí, todas las páginas se entregan optimizadas para un posicionamiento SEO excelente." },
            { question: "¿Puedo pedir cambios?", answer: "Sí, se incluyen revisiones para garantizar que el resultado final supere tus expectativas." },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
