// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardCarousel from '@/components/sections/hero/HeroBillboardCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection): React.JSX.Element {
  return 
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardCarousel
          tag="Agencia Premium de Diseño"
          title="Diseño páginas web profesionales que convierten visitantes en clientes."
          description="Creo páginas web rápidas, optimizadas para SEO, modernas y totalmente adaptadas a cualquier negocio."
          primaryButton={{
            text: "Solicitar presupuesto",        href: "#contacto"}}
          secondaryButton={{
            text: "Ver trabajos",        href: "#servicios"}}
          items={[
            { imageSrc: "http://img.b2bpic.net/free-vector/business-landing-page-concept_23-2148313956.jpg" },
            { imageSrc: "http://img.b2bpic.net/free-photo/computer-laptop-phone-screen-with-abstract-marble-aesthetic_53876-153479.jpg" },
            { imageSrc: "http://img.b2bpic.net/free-vector/gradient-ui-ux-landing-page_52683-69729.jpg" },
            { imageSrc: "http://img.b2bpic.net/free-photo/man-switching-bulbs-using-voice-command-tablet_482257-8730.jpg" },
            { imageSrc: "https://images.pexels.com/photos/5583972/pexels-photo-5583972.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=5583972" },
            { imageSrc: "http://img.b2bpic.net/free-photo/person-working-laptop-cafe-with-coffee_9975-24570.jpg" },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
