// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "proceso" section.

import React from 'react';
import FeaturesBento from '@/components/sections/features/FeaturesBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProcesoSection): React.JSX.Element {
  return 
    <div id="proceso" data-section="proceso">
        <SectionErrorBoundary name="proceso">
              <FeaturesBento
          tag="Metodología"
          title="Mi proceso de trabajo"
          description="Un método ágil y transparente diseñado para garantizar el éxito."
          features={[
            {
              title: "Fases de creación",          description: "Cada etapa cuenta para un resultado final de excelencia.",          bentoComponent: "checklist-timeline",          heading: "Proceso",          subheading: "4 pasos claros",          checklistItems: [
                { label: "Contacto", detail: "Analizamos necesidades" },
                { label: "Diseño", detail: "Propuesta profesional" },
                { label: "Desarrollo", detail: "Programación optimizada" },
              ],
              completedLabel: "Entrega"
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
