// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "resenas" section.

import React from 'react';
import TestimonialTrustCard from '@/components/sections/testimonial/TestimonialTrustCard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ResenasSection(): React.JSX.Element {
  return (
    <div id="resenas" data-section="resenas">
        <SectionErrorBoundary name="resenas">
              <TestimonialTrustCard
          quote="Nota: Estas reseñas son ejemplos de diseño y deberán ser reemplazadas por testimonios reales de clientes."
          rating={5}
          author="Reseñas demostrativas (reemplazar)"
          avatars={[
            { name: "Carlos M.", imageSrc: "http://img.b2bpic.net/free-photo/smiling-african-american-girl-sitting-cafe_1262-3083.jpg" },
            { name: "Laura G.", imageSrc: "http://img.b2bpic.net/free-photo/portrait-waitress-standing-with-disposable-coffee-cup_107420-12313.jpg" },
            { name: "Sergio P.", imageSrc: "http://img.b2bpic.net/free-photo/business-woman-posing-street_23-2148213514.jpg" },
            { name: "Marta R.", imageSrc: "http://img.b2bpic.net/free-photo/portrait-man-black-suit_23-2148401442.jpg" },
            { name: "David H.", imageSrc: "http://img.b2bpic.net/free-photo/head-shot-happy-beautiful-young-woman-posing-indoors-looking-camera-smiling_74855-10218.jpg" },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
