// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "servicios" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServiciosSection(): React.JSX.Element {
  return (
    <div id="servicios" data-section="servicios">
        <SectionErrorBoundary name="servicios">
              <FeaturesRevealCardsBento
          tag="Lo que hago"
          title="Servicios web integrales"
          description="Soluciones digitales de alto impacto para negocios ambiciosos."
          items={[
            { title: "Diseño web", description: "Diseños a medida que destacan tu marca profesionalmente.", href: "#", imageSrc: "https://storage.googleapis.com/webild/users/user_3Fp4xaa76hoCedVVjKM5K4THBWm/uploaded-1782762351328-hlhe4ofv.jpg" },
            { title: "Tiendas online", description: "E-commerce optimizados para maximizar las ventas y conversiones.", href: "#", imageSrc: "https://storage.googleapis.com/webild/users/user_3Fp4xaa76hoCedVVjKM5K4THBWm/uploaded-1782762413005-7patmfyt.jpg" },
            { title: "Landing Pages", description: "Páginas diseñadas específicamente para atraer y convertir clientes.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/innovation-development-rocket-graphic-concept_53876-120019.jpg" },
            { title: "Optimización SEO", description: "Posicionamiento en buscadores para atraer tráfico de calidad.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/rocket-ship-launching-symbol-green-paper_53876-144724.jpg" },
            { title: "Diseño Responsive", description: "Adaptabilidad total en todos los dispositivos modernos.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/laptop-wooden-desk-with-social-media-diagram_1134-64.jpg" },
            { title: "Mantenimiento web", description: "Actualizaciones constantes para mantener tu web al día.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/3d-render-pos-terminal-paper-check-bill-cards_107791-17432.jpg" },
            { title: "Velocidad web", description: "Optimización de tiempos de carga críticos para el usuario.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/paper-balls-with-lit-bulb_1232-582.jpg" },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
