// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "ventajas" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function VentajasSection): React.JSX.Element {
  return 
    <div id="ventajas" data-section="ventajas">
        <SectionErrorBoundary name="ventajas">
              <MetricsSimpleCards
          tag="Por qué elegirme"
          title="Resultados comprobados"
          description="La combinación perfecta entre tecnología, diseño y estrategia."
          metrics={[
            { value: "24h", description: "Entrega rápida" },
            { value: "100%", description: "SEO Optimizado" },
            { value: "3+", description: "Años de experiencia" },
            { value: "100%", description: "Soporte personalizado" },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
